### ISSUE TITLE
eSCAPE needs instructions for testing 

### ISSUE THREAD

**Issue by kbarnhart** [Geodels/eSCAPE#2]
This is another issue associated with [this JOSS review](https://github.com/openjournals/joss-reviews/issues/964).

The [review requirements regarding testing](https://joss.readthedocs.io/en/latest/review_criteria.html#tests) recommended having either an automated test suite or a set of "manual steps that can be followed to check the expected functionality of the software (e.g. a sample input file to assert behaviour)".

Given the dependencies of eSCAPE on HPCC-type libraries I can understand why it might be challenging to set up automated tests on standard CI platforms (e.g. Travis).

However, given the large number of (potentially user compiled) dependencies it seems like it would be very good to have one example that could test that eSCAPE produces the expected output. One option would be to provide the `imput_glob.yaml` and `run_espace.py` files discussed [in this part of the wiki](https://github.com/Geodels/eSCAPE/wiki/Installation-on-HPC#example-of-pbs-script) and add some lines to `run_espace.py` that open the output and assert that some values have been calculated correctly.

**Comment by tristan-salles** [comment]
Based on this comment I have provided an additional test in the eSCAPE-demo folder for this purpose:

### Testing eSCAPE installation

The [**eSCAPE-demo**](https://github.com/Geodels/eSCAPE-demo) contains a **test** folder that provides manual steps that can be followed to check the expected functionality of the software.

The **test** proposes tow comparisons related to:

1. the _expected output values_ that you should be obtained if the installation is successful
2. runtime for both _serial_ and _parallel_ simulations

This test should take less than one minute. An example on how to visualise eSCAPE outputs in [**Paraview**](https://www.paraview.org/download/) is also provided.

**Comment by kbarnhart** [comment]
@tristan-salles this is great. 

I'd recommend you explicitly state that this test exists in the `readme.md` for the main eSCAPE repo. 

Something like revising the sentence

> A set of examples are available in the eSCAPE-demo repository.

to 

> A set of examples are available in the eSCAPE-demo repository. These examples include a small test that can be used to verify that the eSCAPE installation is working as expected. 

There is also a very minor typo in the added text. 

> The **test** proposes tow comparisons related to:

should be

> The **test** proposes two comparisons related to:

**Comment by tristan-salles** [comment]
It has been added to the README file and the typo has been fixed! Thanks!
