### ISSUE TITLE
Incomplete documentation related to boundary conditions

### ISSUE THREAD

**Issue by kbarnhart** [Geodels/eSCAPE#7]
I've tried to limit issues related to the [JOSS review](https://github.com/openjournals/joss-reviews/issues/964) to what is outlined in the [review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html). 

There is one aspect of documentation not described in the criteria that I think is missing in eSCAPE. Specifically I can't tell what sort of model-domain edge boundary conditions are used (and if there are any options). This would be a good thing to add to the documentation.

**Comment by tristan-salles** [comment]
Based on reviewer's comment the following paragraph has been added to the input file description in the wiki and model website:

***

Model-domain edge boundary conditions are set using the `bc` element in the YAML input file and the following options are available:

1. `flat`: edges elevations are set to the elevations of the closest non-edge vertices
2. `fixed`: edges elevations remain at the same position during the model run  
3. `slope`: edges elevations are defined based on the closest non-edge vertices average slope

**Comment by kbarnhart** [comment]
Thanks for adding this. I'll close the issue.
